title: Erik Boesen
email: me@erikboesen.com
permalink: /:title  # Clean post URLs
description:
baseurl: ""
url: "https://erikboesen.com"
twitter_username: ErikBoesen
github_username:  ErikBoesen
instagram_username: erikboesen
googleplus_username: ErikBoesen


# Build settings
sass:
    style: compressed
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-twitter-plugin

exclude:
  - Gemfile
  - Gemfile.lock
